apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: order
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          args: ["redis-server", "--requirepass", "password"]
          env:
            - name: REDIS_PASSWORD
              value: "password"
